# Chckout Numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([[2, 3, 4, 677]], np.int32)

In [3]:
myarr

array([[  2,   3,   4, 677]])

In [4]:
myarr[0]

array([  2,   3,   4, 677])

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int32')

In [7]:
myarr[0, 1] = 45

In [8]:
myarr

array([[  2,  45,   4, 677]])

In [9]:
myarr

array([[  2,  45,   4, 677]])

# Array Creation: Conversion from other python structure

In [10]:
listarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [11]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.shape


(3, 3)

In [14]:
listarray.size

9

In [15]:
np.array({23, 34, 56})

array({56, 34, 23}, dtype=object)

In [16]:
zeros = np.zeros((2, 5))

In [17]:
zeros.size

10

In [18]:
rng = np.arange(15)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace = np.linspace(1, 5, 12)

In [21]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [22]:
emp = np.empty((4, 6))

In [23]:
emp

array([[1.68e-321, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000]])

In [24]:
ide = np.identity(45)

In [25]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [26]:
ide.size

2025

In [27]:
rg = np.arange(90)

In [28]:
rg

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [29]:
rg.reshape(3, 30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [30]:
rg = rg.reshape(3, 30)

In [31]:
rg

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [32]:
rg = rg.ravel()

In [33]:
rg

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [34]:
rg.shape

(90,)

In [35]:
ar = np.array([[1, 2, 3], [5, 6, 7], [8, 9, 0]])


In [36]:
ar.sum(axis=0)


array([14, 17, 10])

In [37]:
ar.sum(axis=1)

array([ 6, 18, 17])

In [38]:
ar.T

array([[1, 5, 8],
       [2, 6, 9],
       [3, 7, 0]])

In [41]:
list(ar.flat)

[1, 2, 3, 5, 6, 7, 8, 9, 0]

In [42]:
ar.nbytes

36

In [43]:
ar.shape

(3, 3)

In [44]:
ar.size

9

In [52]:
one = np.array([1, 2, 3, 454, 2])

In [47]:
one.argmax

<function ndarray.argmax>

In [48]:
one.argmax()

3

In [49]:
one[one.argmax()]

454

In [50]:
one.argmin()

0

In [54]:
one.argsort()

array([0, 1, 4, 2, 3], dtype=int64)

In [55]:
ar.argmin()

8

In [56]:
ar.argmax()

7

In [57]:
ar

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [58]:
ar.argmin(axis=0)

array([0, 0, 2], dtype=int64)

In [59]:
ar.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [60]:
ar.argsort(axis=0)

array([[0, 0, 2],
       [1, 1, 0],
       [2, 2, 1]], dtype=int64)

In [61]:
ar.ravel()

array([1, 2, 3, 5, 6, 7, 8, 9, 0])

In [65]:
ar.reshape((9, 1))

array([[1],
       [2],
       [3],
       [5],
       [6],
       [7],
       [8],
       [9],
       [0]])

In [66]:
ar

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [67]:
ar2 = np.array([[1, 2, 3],
       [5, 1, 2],
       [8, 1, 0]])

In [68]:
ar + ar2

array([[ 2,  4,  6],
       [10,  7,  9],
       [16, 10,  0]])

In [69]:
ar*ar2

array([[ 1,  4,  9],
       [25,  6, 14],
       [64,  9,  0]])

In [70]:
np.where(ar>5)

(array([1, 1, 2, 2], dtype=int64), array([1, 2, 0, 1], dtype=int64))

In [71]:
ar

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [72]:
type(np.where(ar))

tuple